### ISSUE TITLE
error when trying to run scid2pgn

### ISSUE THREAD

**Issue by Jonathan003** [CasualPyDev/pgn2scid#4]
I'm trying to convert a pgn to the Scid format with scid2pgn, but I get an error message.
The latest version of Python is installed om my Windows 11 64 bit PC
I also have the latest version of Scid vs PC and Scid, installed on my PC.
I get the error message:
`pgnscid not found
©Unable to locate pgnscid! Either pgnscid' is not installed properly or not in SPATH`

I don't know what I do wrong?
I have made a video capture of it:

https://user-images.githubusercontent.com/40061628/152666970-edb60e0e-be2d-471d-9b9b-14a8300badc9.mp4

**Comment by CasualPyDev** [comment]
Hi Jonathan,

Are you able to start pgnscid using the Windows command line interface
(CMD)? It seems that pgn2scid can't locate the installation folder of Scid
vs PC, which also contains pgnscid.

Greetings,
Andreas

**Comment by Jonathan003** [comment]
Sorry for my late reply.
Some things got in the way and I forgot about it.
Yes I can run the commend line tool pgnscid located here
C:\Scid vs PC-4.22\bin
and convert pgn files that way.
But I have problems converting a huge pgn file to Scid.
I get error messages saying "to many player names" or something.
This is the pgn database I have tried to convert
http://rebel13.nl/dl.html?file=dl/human.7z

Is there a size limitation to convert pgn files to Scid format? Can I convert a pgn database with 90 million games to scid? 
I have read somewhere that it sometimes helps to remove site and round tags in a pgn file with a text editor that can handle huge text files. Before trying to convert a huge pgn file to pgn.

**Comment by CasualPyDev** [comment]
When the command line tool works, then there's clearly a path entry, pointing to your Scid vs PC installation, missing in your PATH environment variable. To check that you have to open the command processor cmd and type 'echo $PATH'. You then get a list of all search paths where Windows looks for commands and programs. Please check whether the installation path of Scid vs PC is included here. If it's not there, you have to add it manually.

Concerning your database, I'm wondering where to get a database with 90 million games? The biggest databases I'm aware of contain roughly 9 million games (e.g. the ChessBase DB), some really huge ones 11 millions, my personal database has 7 million games and this even goes back to Napoleon Bonaparte. But 90 million games? What is the source of this database?
However, unfortunately I'm not the developer of the converting tool per se, so I can't tell you if there's a practical limit of games which can be converted. Maybe you could split the database, because if it's a pgn based DB, it should just be an ASCII text file.

**Comment by Jonathan003** [comment]
This is what I get if I type 'echo $PATH'
![Screenshot echo $PATH'png](https://user-images.githubusercontent.com/40061628/155529387-b4dde01e-9126-483c-adb8-4a6cee0d5841.png)

This it the installation path of Scid vs Pc where also the file pgnscid.exe is located.
C:\Scid vs PC-4.22\bin
How can I ad this path? Sorry for my maybe stupid questions, but I don't have any programming knowledge.

About the huge database with 90 million games.
I have downloaded the games here https://database.lichess.org/

I try to filter the huge pgn database with this new tool https://github.com/nguyenpham/ocgdb/releases/tag/VersionBeta7

**Comment by CasualPyDev** [comment]
Oh sorry, under Windows it should be echo  %PATH%

**Comment by Jonathan003** [comment]
This is what I get if I type echo %PATH%
![Screenshot CMD](https://user-images.githubusercontent.com/40061628/155894164-5a3c5632-938d-4875-955c-c76c8c73ff8b.png)

How can I add 
C:\Scid vs PC-4.22\bin

**Comment by CasualPyDev** [comment]
https://www.computerhope.com/issues/ch000549.htm

**Comment by Jonathan003** [comment]
Thanks for the explanation. I was able to ad C:\Scid vs PC-4.22\bin to the path
![Screenshot CMD](https://user-images.githubusercontent.com/40061628/156432448-addec18a-6b08-462d-b0ef-563fcd4e7fd1.png)

I'm still not able to successfully convert pgn files to the scid format using the tool.
I have made a video capture: 

https://user-images.githubusercontent.com/40061628/156432508-7d71fc71-54e7-4567-bc57-773d60601ff8.mp4

**Comment by CasualPyDev** [comment]
Could you send me both pgn files, please?

**Comment by Jonathan003** [comment]
Here is a link to the working path file with the two pgn files:
[working path](https://drive.google.com/drive/folders/10nEF_BfoGDa2ouPV4Ad38kHEgmdC1-nv?usp=sharing)

**Comment by CasualPyDev** [comment]
Both files are processed without problems on my Linux machine. Please start pgn2scid using your terminal and see if there are any errors.

**Comment by Jonathan003** [comment]
I'm not sure what you mean with stating pgn2scid using terminal?
You mean in stead of double clicking pgn2scid to run it from the command prompt like in this video? 

https://user-images.githubusercontent.com/40061628/158067026-8deb820e-bb15-471d-9ecc-83641718a5b4.mp4

**Comment by CasualPyDev** [comment]
Hi,
sorry for my late answer, I don't have much time at the moment. I'll create a debug version of pgn2scid to send it to you so that you can test it. I hope to get some more insights then.
